# Generated by Django 4.2.5 on 2023-09-20 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of item', max_length=25)),
                ('price', models.IntegerField(help_text='price of item')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='review text')),
                ('rating', models.IntegerField(help_text='the rating the reviewer has given')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='date and time of review')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.OneToOneField(help_text='the item being sold', on_delete=django.db.models.deletion.CASCADE, to='reviews.item')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='sellers first name', max_length=50)),
                ('last_name', models.CharField(help_text='sellers last name', max_length=50)),
                ('seller_email', models.EmailField(help_text='sellers email address', max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.OneToOneField(help_text='the seller of the item', on_delete=django.db.models.deletion.CASCADE, to='reviews.seller'),
        ),
    ]
