# Generated by Django 4.2.5 on 2023-10-12 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the item', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the item', max_digits=10)),
                ('descriptions', models.TextField(default='No description.', help_text='Description of the item', max_length=250)),
                ('image', models.ImageField(default='../static/404.png', help_text='Image of the item', upload_to='product_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
