# Generated by Django 4.2.5 on 2023-09-22 00:24

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0002_alter_seller_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the item', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the item', max_digits=10)),
                ('descriptions', models.TextField(default='No description.', help_text='Description of the item', max_length=250)),
                ('image', models.ImageField(default='media/404.png', help_text='Image of the item', upload_to='product_images/')),
                ('seller', models.ForeignKey(default=products.models.Item.get_default_seller, help_text='The seller of the item', on_delete=django.db.models.deletion.CASCADE, to='sellers.seller')),
            ],
        ),
    ]
