# Generated by Django 4.2.6 on 2023-10-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='../static/404.png', help_text='Image of the item', upload_to='product_images/'),
        ),
    ]
