# Generated by Django 4.2.5 on 2023-09-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the seller', max_length=50)),
                ('email', models.EmailField(help_text='Email address of the seller', max_length=254)),
            ],
        ),
    ]
